/**
 * Utility functions for exporting analysis results to markdown format.
 */

import { Status, Verdict } from './constants';

// Type definitions for analysis results
export interface FactCheck {
  claim: string;
  verdict: Verdict;
  confidence: number;
  evidence?: string;
  sources?: string[];
}

export interface AnalysisResults {
  id: string;
  transcript_filename?: string;
  transcript_title?: string;
  status: Status;
  completed_at?: string;
  summary?: string;
  takeaways?: string[];
  fact_checks?: FactCheck[];
}

/**
 * Generate markdown content from analysis results
 */
export const generateMarkdown = (results: AnalysisResults): string => {
  if (!results) return '';

  const sections: string[] = [];

  // Header
  sections.push('# Podcast Analysis Results');
  sections.push('');

  // Analysis Info
  sections.push('## Analysis Information');
  sections.push('');
  sections.push(`**Analysis ID:** ${results.id}`);
  sections.push(`**Source File:** ${results.transcript_filename || 'Unknown'}`);
  if (results.transcript_title && results.transcript_title !== results.transcript_filename) {
    sections.push(`**Title:** ${results.transcript_title}`);
  }
  sections.push(`**Status:** ${results.status}`);
  sections.push(`**Completed:** ${results.completed_at ? new Date(results.completed_at).toLocaleString() : 'N/A'}`);
  sections.push('');

  // Summary
  if (results.summary) {
    sections.push('## Summary');
    sections.push('');
    sections.push(results.summary);
    sections.push('');
  }

  // Key Takeaways
  if (results.takeaways && results.takeaways.length > 0) {
    sections.push('## Key Takeaways');
    sections.push('');
    results.takeaways.forEach((takeaway, index) => {
      sections.push(`${index + 1}. ${takeaway}`);
    });
    sections.push('');
  }

  // Fact Check Results
  if (results.fact_checks && results.fact_checks.length > 0) {
    sections.push('## Fact Check Results');
    sections.push('');
    
    results.fact_checks.forEach((factCheck, index) => {
      sections.push(`### Claim ${index + 1}`);
      sections.push('');
      sections.push(`**Claim:** ${factCheck.claim}`);
      sections.push(`**Verdict:** ${factCheck.verdict.toUpperCase()}`);
      sections.push(`**Confidence:** ${(factCheck.confidence * 100).toFixed(1)}%`);
      
      if (factCheck.evidence) {
        sections.push(`**Evidence:** ${factCheck.evidence}`);
      }
      
      if (factCheck.sources && factCheck.sources.length > 0) {
        sections.push('**Sources:**');
        factCheck.sources.forEach(source => {
          sections.push(`- ${source}`);
        });
      }
      sections.push('');
    });
  }

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('*Generated by Podcast Analyzer*');
  sections.push(`*Export Date: ${new Date().toLocaleString()}*`);

  return sections.join('\n');
};

/**
 * Download markdown content as a file
 */
export const downloadMarkdown = (content: string, filename: string = 'analysis-results.md'): void => {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  
  // Cleanup
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Generate filename for the markdown export
 */
export const generateFilename = (results: AnalysisResults): string => {
  if (!results) return 'analysis-results.md';
  
  const date = results.completed_at 
    ? new Date(results.completed_at).toISOString().split('T')[0]
    : new Date().toISOString().split('T')[0];
  
  const analysisId = results.id ? results.id.substring(0, 8) : 'unknown';
  
  // Extract base filename without extension from transcript filename
  let baseFilename = 'transcript';
  if (results.transcript_filename) {
    // Remove file extension (.txt, .json, etc.)
    baseFilename = results.transcript_filename.replace(/\.[^/.]+$/, '');
    // Replace spaces and special chars with hyphens for clean filename
    baseFilename = baseFilename.replace(/[^a-zA-Z0-9-_]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
  }
  
  return `analysis-${baseFilename}-${analysisId}-${date}.md`;
};