/**
 * Tests for markdown exporter utility functions.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { generateMarkdown, downloadMarkdown, generateFilename } from '../../src/utils/markdownExporter';

describe('markdownExporter', () => {
  describe('generateMarkdown', () => {
    it('returns empty string for null results', () => {
      const result = generateMarkdown(null);
      expect(result).toBe('');
    });

    it('returns empty string for undefined results', () => {
      const result = generateMarkdown(undefined);
      expect(result).toBe('');
    });

    it('generates basic markdown with minimal data', () => {
      const results = {
        id: 'test-id',
        status: 'completed',
        completed_at: '2024-01-01T12:00:00Z'
      };

      const markdown = generateMarkdown(results);
      
      expect(markdown).toContain('# Podcast Analysis Results');
      expect(markdown).toContain('## Analysis Information');
      expect(markdown).toContain('**Analysis ID:** test-id');
      expect(markdown).toContain('**Status:** completed');
      expect(markdown).toContain('*Generated by Podcast Analyzer*');
    });

    it('includes summary when provided', () => {
      const results = {
        id: 'test-id',
        status: 'completed',
        completed_at: '2024-01-01T12:00:00Z',
        summary: 'This is a test summary of the podcast analysis.'
      };

      const markdown = generateMarkdown(results);
      
      expect(markdown).toContain('## Summary');
      expect(markdown).toContain('This is a test summary of the podcast analysis.');
    });

    it('includes takeaways when provided', () => {
      const results = {
        id: 'test-id',
        status: 'completed',
        completed_at: '2024-01-01T12:00:00Z',
        takeaways: [
          'First key takeaway',
          'Second key takeaway',
          'Third key takeaway'
        ]
      };

      const markdown = generateMarkdown(results);
      
      expect(markdown).toContain('## Key Takeaways');
      expect(markdown).toContain('1. First key takeaway');
      expect(markdown).toContain('2. Second key takeaway');
      expect(markdown).toContain('3. Third key takeaway');
    });

    it('includes fact checks when provided', () => {
      const results = {
        id: 'test-id',
        status: 'completed',
        completed_at: '2024-01-01T12:00:00Z',
        fact_checks: [
          {
            claim: 'Test claim about technology',
            verdict: 'true',
            confidence: 0.95,
            evidence: 'Strong evidence from reliable sources',
            sources: ['https://example.com/source1', 'https://example.com/source2']
          },
          {
            claim: 'Another test claim',
            verdict: 'unverifiable',
            confidence: 0.2,
            evidence: 'Insufficient information available'
          }
        ]
      };

      const markdown = generateMarkdown(results);
      
      expect(markdown).toContain('## Fact Check Results');
      expect(markdown).toContain('### Claim 1');
      expect(markdown).toContain('**Claim:** Test claim about technology');
      expect(markdown).toContain('**Verdict:** TRUE');
      expect(markdown).toContain('**Confidence:** 95.0%');
      expect(markdown).toContain('**Evidence:** Strong evidence from reliable sources');
      expect(markdown).toContain('**Sources:**');
      expect(markdown).toContain('- https://example.com/source1');
      expect(markdown).toContain('- https://example.com/source2');
      
      expect(markdown).toContain('### Claim 2');
      expect(markdown).toContain('**Claim:** Another test claim');
      expect(markdown).toContain('**Verdict:** UNVERIFIABLE');
      expect(markdown).toContain('**Confidence:** 20.0%');
    });

    it('handles empty arrays gracefully', () => {
      const results = {
        id: 'test-id',
        status: 'completed',
        completed_at: '2024-01-01T12:00:00Z',
        takeaways: [],
        fact_checks: []
      };

      const markdown = generateMarkdown(results);
      
      expect(markdown).toContain('# Podcast Analysis Results');
      expect(markdown).toContain('## Analysis Information');
      expect(markdown).not.toContain('## Key Takeaways');
      expect(markdown).not.toContain('## Fact Check Results');
    });

    it('handles fact checks without sources', () => {
      const results = {
        id: 'test-id',
        status: 'completed',
        completed_at: '2024-01-01T12:00:00Z',
        fact_checks: [
          {
            claim: 'Test claim',
            verdict: 'false',
            confidence: 0.8,
            evidence: 'Contradictory evidence found',
            sources: []
          }
        ]
      };

      const markdown = generateMarkdown(results);
      
      expect(markdown).toContain('**Verdict:** FALSE');
      expect(markdown).toContain('**Evidence:** Contradictory evidence found');
      expect(markdown).not.toContain('**Sources:**');
    });
  });

  describe('generateFilename', () => {
    it('returns default filename for null results', () => {
      const filename = generateFilename(null);
      expect(filename).toBe('analysis-results.md');
    });

    it('returns default filename for undefined results', () => {
      const filename = generateFilename(undefined);
      expect(filename).toBe('analysis-results.md');
    });

    it('generates filename with transcript name, analysis ID and date', () => {
      const results = {
        id: 'abcd1234-5678-90ef-ghij-klmnopqrstuv',
        completed_at: '2024-01-15T14:30:00Z',
        transcript_filename: 'my-podcast.txt'
      };

      const filename = generateFilename(results);
      expect(filename).toBe('analysis-my-podcast-abcd1234-2024-01-15.md');
    });

    it('uses current date when completed_at is not provided', () => {
      const results = {
        id: 'test-id-123',
        transcript_filename: 'test file.json'
      };

      // Mock the current date
      const mockDate = new Date('2024-12-13T10:00:00Z');
      vi.setSystemTime(mockDate);

      const filename = generateFilename(results);
      expect(filename).toBe('analysis-test-file-test-id--2024-12-13.md');
      
      vi.useRealTimers();
    });

    it('handles missing ID gracefully', () => {
      const results = {
        completed_at: '2024-01-15T14:30:00Z',
        transcript_filename: 'podcast.txt'
      };

      const filename = generateFilename(results);
      expect(filename).toBe('analysis-podcast-unknown-2024-01-15.md');
    });

    it('uses transcript fallback when transcript_filename is missing', () => {
      const results = {
        id: 'test123',
        completed_at: '2024-01-15T14:30:00Z'
      };

      const filename = generateFilename(results);
      expect(filename).toBe('analysis-transcript-test123-2024-01-15.md');
    });
  });

  describe('downloadMarkdown', () => {
    let createElementSpy;
    let appendChildSpy;
    let removeChildSpy;
    let createObjectURLSpy;
    let revokeObjectURLSpy;

    beforeEach(() => {
      // Mock DOM methods
      const mockElement = {
        href: '',
        download: '',
        click: vi.fn()
      };

      createElementSpy = vi.spyOn(document, 'createElement').mockReturnValue(mockElement);
      appendChildSpy = vi.spyOn(document.body, 'appendChild').mockImplementation(() => {});
      removeChildSpy = vi.spyOn(document.body, 'removeChild').mockImplementation(() => {});

      // Mock URL methods - create if doesn't exist
      if (typeof URL === 'undefined') {
        global.URL = {};
      }
      if (!URL.createObjectURL) {
        URL.createObjectURL = vi.fn();
      }
      if (!URL.revokeObjectURL) {
        URL.revokeObjectURL = vi.fn();
      }
      
      createObjectURLSpy = vi.spyOn(URL, 'createObjectURL').mockReturnValue('mock-url');
      revokeObjectURLSpy = vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => {});
    });

    afterEach(() => {
      vi.restoreAllMocks();
    });

    it('creates download link with correct attributes', () => {
      const content = '# Test Markdown\n\nThis is test content.';
      const filename = 'test-file.md';

      downloadMarkdown(content, filename);

      // Verify element creation
      expect(createElementSpy).toHaveBeenCalledWith('a');
      
      // Verify blob creation and URL
      expect(createObjectURLSpy).toHaveBeenCalled();
      const blob = createObjectURLSpy.mock.calls[0][0];
      expect(blob).toBeInstanceOf(Blob);
      expect(blob.type).toBe('text/markdown;charset=utf-8');

      // Verify DOM manipulation
      expect(appendChildSpy).toHaveBeenCalled();
      expect(removeChildSpy).toHaveBeenCalled();
      expect(revokeObjectURLSpy).toHaveBeenCalledWith('mock-url');
    });

    it('uses default filename when not provided', () => {
      const content = '# Test';

      downloadMarkdown(content);

      // Should still work without errors
      expect(createElementSpy).toHaveBeenCalledWith('a');
    });

    it('handles empty content', () => {
      downloadMarkdown('');

      expect(createElementSpy).toHaveBeenCalledWith('a');
      expect(createObjectURLSpy).toHaveBeenCalled();
    });
  });
});